### ISSUE TITLE
`stable` documentation did not update with `v0.2.5`; the `dev` documentation is now up to date though

### ISSUE THREAD

**Issue by gaelforget** [JuliaClimate/MeshArrays.jl#36]
Previous release (`v0.2.5`) included major updates in e.g. `docs/src/index.md` but  [https://juliaclimate.github.io/MeshArrays.jl/stable/]() did not reflect the updates. The reason is explained below.

Until next release (`v0.2.6`) please refer to [https://juliaclimate.github.io/MeshArrays.jl/dev/]() that has been updated

**Comment by gaelforget** [comment]
@balinus maybe you have a tip or guess that could help me resolve this issue?

I noticed that the `gh-pages` branch of `climatetools.jl` is getting updated whereas `Mesharrays` did not -- that's why I wonder if you might know what I may have overlooked.

**Comment by gaelforget** [comment]
> @Balinus maybe you have a tip or guess that could help me resolve this issue?
> 
> I noticed that the `gh-pages` branch of `climatetools.jl` is getting updated whereas `Mesharrays` did not -- that's why I wonder if you might know what I may have overlooked.

Found it! Sorry I was so quick at pinging you. I had forgotten to update the deploydocs repo specification in `docs/make.jl`. 

Will document my steps when migrating next package and might add that `how-to` somewhere in the issue tracker of [https://github.com/JuliaClimate/meta]() if that makes sense

**Comment by gaelforget** [comment]
@suyashbire1

**Comment by Balinus** [comment]
Had the same problem!

Did you do a release since you migrated? You're gonna need to to a PR in General like this: https://github.com/JuliaRegistries/General/pull/8323

**Comment by Balinus** [comment]
Ah, just saw you referenced this.

**Comment by Balinus** [comment]
did you succeeded in updating the documentation? Seems like my latest tagged release was not updated.

**Comment by gaelforget** [comment]
> did you succeeded in updating the documentation? Seems like my latest tagged release was not updated.

Yes -- seems all set based on new release I did just now after merging PR #37

So I am closing this PR. Thanks @Balinus for following up earlier
